### ISSUE TITLE
Sensoren ein und ausschalten

### ISSUE THREAD

**Issue by ScharV** [TiPunch69/homebridge-awtrix-plugin#2]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**
Es wäre nice to have, wenn man durch true und false auswählen könnte, ob Temperatur und Luftfeuchtigkeitssensoren vorhanden sind und mit an HomeKit übergeben werden sollen.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by TiPunch69** [comment]
This is not a problem, I can add it to the next version. Currently I am on holidays, so this will be around 20/08/2021.
